import { Arimo } from "next/font/google";
import "./globals.css";

const arimo = Arimo({
  variable : "--font-arimo",
  subsets :['latin']
})

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${arimo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
